### ISSUE TITLE
Change the image of the Login Page background

### ISSUE THREAD

**Issue by IvonArroyo** [mmicciolo/wearable-learning-cloud-platform#33]
We have to change the image background of the Login page to something that is more like game creation, or embodied stuff, or images of kids playing games.

**Comment by IvonArroyo** [comment]
Pictures that could be tiled to form a background for this are attached.

![Uploading KidsPlayingGames.pptx…]()
![Uploading MASSAcadStudentsMeasurng.JPG…]()
![Uploading NicoJumping.jpg…]()
![Uploading TeamRunningBack.png…]()
![Uploading TouchTomorrow1.jpg…]()
![Uploading WLCPEDITOR.png…]()
![Uploading WPI916669.jpg…]()








[Uploading GameEditor_EstimateIt2.PNG…]()
me
![Uploading DSC00976.jpg…]()
![Uploading DSC00983.jpg…]()
![Uploading FavoriteSmall.jpeg…]()
![Uploading Game Scene.jpg…]()
![Uploading GameDash.JPG…]()




 images that could be tiled and be the background.
![Uploading Ateneo Gradeschool First Team To Finish Game Only Group.JPG…]()

**Comment by mmicciolo** [comment]
FIxed in V0.0.3-RELEASE
